package testes;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class UC01ConsultaCEPFormVazio {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\cadua\\eclipse-workspace\\testesselenium\\browserDriver\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void CT03ConsultaCEPcomLogradouroEmBranco() {
		driver.get("http://www.buscacep.correios.com.br/sistemas/buscacep/buscaCep.cfm");
		driver.manage().window().setSize(new Dimension(1366, 768));
		driver.findElement(By.name("UF")).click();
		{
			WebElement dropdown = driver.findElement(By.name("UF"));
			dropdown.findElement(By.xpath("//option[. = 'SP']")).click();
		}
		driver.findElement(By.name("UF")).click();
		driver.findElement(By.name("Localidade")).click();
		driver.findElement(By.name("Localidade")).sendKeys("São Paulo");
		driver.findElement(By.cssSelector(".contentform")).click();
		driver.findElement(By.name("Tipo")).click();
		{
			WebElement dropdown = driver.findElement(By.name("Tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Rua']")).click();
		}
		driver.findElement(By.name("Tipo")).click();
		driver.findElement(By.name("Logradouro")).click();
		driver.findElement(By.cssSelector(".btn2")).click();
		assertThat(driver.switchTo().alert().getText(), is("Informe o logradouro !"));
	}
}